# Generated by Django 4.2.6 on 2023-10-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_pleasurable', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.IntegerField(default=1, verbose_name='период выполнения, в днях')),
                ('reward', models.CharField(max_length=250, verbose_name='награда')),
                ('duration', models.IntegerField(default=0, verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('send_time', models.TimeField(auto_now=True, null=True, verbose_name='Время отправки')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
